---
k: all
retriever: dense
query_file: asqa_eval.json
query_dataset: asqa
doc_dataset: dpr_wiki
output_file: asqa_retrieval-bge-base-all-rest.json
embed_file: dpr_wiki-bge1.5-base.fvecs
embed_model_name: BAAI/bge-base-en-v1.5
embed_model_type: 'st'
num_threads: 112
