---
k: 10
num_threads: 112
text_key: contents
retriever: dense
query_file: bioasq_qa.json
query_dataset: bioasq
doc_dataset: pubmed
output_file: bioasq_retrieval_ann-recall0.7_bge-base-dense.json
embed_file: pubmed-bge1.5-base.fvecs
embed_model_name: BAAI/bge-base-en-v1.5
embed_model_type: 'st'
index_fn: pysvs.Vamana
dist_type: pysvs.DistanceType.MIP
doc_dtype: pysvs.float16
index_kwargs: {'vamana_build_params': {'alpha': 0.95, 'graph_max_degree': 128, 'window_size': 256, 'max_candidate_pool_size': 512, 'prune_to': 124}}
#search_win_size: 1024
calib_kwargs: {'calib_prefix': bioasq_bge-base-dense, 'num_neighbors': 10, 'target_recall': 0.7}
