---
k: 150
num_threads: 112
text_key: contents
retriever: dense
query_file: bioasq_qa.json
query_dataset: bioasq
doc_dataset: pubmed
output_file: bioasq_retrieval-bge-base-dense-150.json
embed_file: pubmed-bge1.5-base.fvecs
embed_model_name: BAAI/bge-base-en-v1.5
embed_model_type: 'st'
