---
k: 10
num_threads: 144
text_key: text
retriever: dense
query_file: nq_qa.json
query_dataset: nq
doc_dataset: kilt_wikipedia
output_file: nq_retrieval_ann-recall0.7_bge-base-dense.json
embed_file: kilt_wikipedia-bge1.5-base_fp16.fvecs
embed_model_name: BAAI/bge-base-en-v1.5
embed_model_type: 'st'
index_fn: pysvs.Vamana
dist_type: pysvs.DistanceType.MIP
doc_dtype: pysvs.float16
index_kwargs: {'vamana_build_params': {'alpha': 0.95, 'graph_max_degree': 128, 'window_size': 256, 'max_candidate_pool_size': 512, 'prune_to': 124}}
#search_win_size: 1024
calib_kwargs: {'calib_prefix': nq_bge-base-dense, 'num_neighbors': 10, 'target_recall': 0.7}
