---
k: all
retriever: dense
query_file: bioasq_qa.json
doc_dataset: pubmed
output_file: bioasq_retrieval-bge-base-all.json
embed_file: pubmed-bge1.5-base.fvecs
embed_model_name: BAAI/bge-base-en-v1.5
embed_model_type: 'st'
num_threads: 256
noise_experiment: True
