---
prompt_file: any_nocite.json
eval_file: asqa_retrieval-bge-base-dense.json
shot: 0
ndoc: 1
dataset_name: asqa
model: mistralai/Mistral-7B-Instruct-v0.3
temperature: 1.0
top_p: 0.95
max_length: 32768
