---
prompt_file: asqa_cite.json
eval_file: asqa_retrieval-bge-large-dense.json
shot: 2
ndoc: 100
dataset_name: asqa
model: mistralai/Mistral-7B-Instruct-v0.3
temperature: 1.0
top_p: 0.95
max_length: 32768
