---
prompt_file: bioasq_default.json
eval_file: bioasq_retrieval-bge-large-dense.json
shot: 0
ndoc: 5
dataset_name: bioasq
model: mistralai/Mistral-7B-Instruct-v0.3
temperature: 1.0
top_p: 0.95
max_length: 32768
